In [1]:
import pandas as pd
import numpy as np 
import scipy.stats as stats

In [2]:
# first, a sample of a short array of probs 
p = [0.1, 0.5, 0.4]

entropy = stats.entropy(p)
entropy

0.9433483923290392

In [4]:
- (0.1 * np.log(0.1) + 0.5 * np.log(0.5) + 0.4 * np.log(0.4))

0.9433483923290392

In [8]:
# what if I have a matrix
m = np.array([
    p,
    p
])
print("Entropy:\n\n" , m)

stats.entropy(m, axis=1)

Entropy:

 [[0.1 0.5 0.4]
 [0.1 0.5 0.4]]


array([0.94334839, 0.94334839])