In [1]:
%cd ..

/home/juanhevia/IDIL


In [2]:
import os 
import numpy as np 
import pickle as pkl 

TRAJ_PATH = "idil_train/experts/FrankaKitchen-v0-mixed_260_0_1_2.pkl"

In [3]:
with open(TRAJ_PATH, "rb") as f:
    trajs = pkl.load(f)

In [4]:
trajs.keys()

dict_keys(['states', 'next_states', 'actions', 'rewards', 'latents', 'lengths', 'dones'])

In [5]:
len(trajs["states"])

61

In [6]:
len(trajs["states"][0])

176

In [7]:
trajs["states"][0].shape

(176, 59)

In [12]:
lengths = np.array([trajs["lengths"][i] for i in range(len(trajs["lengths"]))])
rews_len = np.array([trajs["rewards"][i].shape[0] for i in range(len(trajs["rewards"]))])

In [13]:
lengths[:10] , rews_len[:10]

(array([176, 176, 187, 198, 189, 184, 186, 190, 191, 179]),
 array([176, 176, 187, 198, 189, 184, 186, 190, 191, 179]))

In [10]:
# check if all lengths are equal to the length of the states
assert all([l == r for l, r in zip(lengths, rews_len)])

AssertionError: 

In [14]:
lengths - rews_len

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 2, 6,
       4, 4, 3, 5, 3, 7, 5, 8, 8, 2, 3, 4, 4, 5, 4, 2, 0, 4, 6, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Fix and reload the file

In [16]:
with open(TRAJ_PATH, "rb") as f:
    trajs = pkl.load(f)

In [17]:
trajs.keys()

dict_keys(['states', 'next_states', 'actions', 'rewards', 'latents', 'lengths', 'dones'])

In [18]:
len(trajs["states"])

61

In [19]:
len(trajs["states"][0])

176

In [20]:
trajs["states"][0].shape

(176, 59)

In [21]:
lengths = np.array([trajs["lengths"][i] for i in range(len(trajs["lengths"]))])
rews_len = np.array([trajs["rewards"][i].shape[0] for i in range(len(trajs["rewards"]))])

In [22]:
lengths[:10] , rews_len[:10]

(array([176, 176, 187, 198, 189, 184, 186, 190, 191, 179]),
 array([176, 176, 187, 198, 189, 184, 186, 190, 191, 179]))

In [23]:
# check if all lengths are equal to the length of the states
assert all([l == r for l, r in zip(lengths, rews_len)])

In [24]:
lengths - rews_len

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])